### ISSUE TITLE
timeout parameter not working

### ISSUE THREAD

**Issue by exa-nakamura** [stetsmando/pi-camera#10]
hi.

now version, timeout parameter in flags.json.
but configToArray function loop continue FLAGS object.
and option parameters not setting.
i want to delete timeout parameter in FLAGS object.

```
PiCamera.prototype.configToArray = function() {
  let configArray = [];
    for (let prop in this.config) {
      if (FLAGS.includes(prop) && this.config[prop]) {  //<-- FLAGS.timeout == true
        configArray.push(`--${ prop }`);
        continue;  //<-- continue, restart loop
      }

      if (OPTS.includes(prop)) {
        configArray.push(`--${ prop }`);
        configArray.push(this.config[prop]);  //<-- OPTS.timeout, not work
        continue;
      }
    }

  return configArray;
}
```

**Comment by stetsmando** [comment]
Sorry but I'm honestly not sure what it is you're getting at. Can you try and ask it in a different way?

**Comment by stetsmando** [comment]
@exa-nakamura Any update on this?

**Comment by stetsmando** [comment]
I'm closing this for now. Feel free to open another issue if you're still having issues.
