### ISSUE TITLE
Node engine extremely restrictive

### ISSUE THREAD

**Issue by cSchubes** [stetsmando/pi-camera#11]
Hi,

I want to use this project in a project whose node engine is required to be ^8.9.0. Because of this I cannot install pi-camera as it throws `The engine "node" is incompatible with this module. Expected version "~6.10.0"`.

This version is defined in the package.json for this project. Does the library only run in node 6 or is this just an oversight?

Thanks

**Comment by stetsmando** [comment]
When I wrote this lib a while back I was running it in a node 6 env and was concerned about it not working on older versions. What I would suggest is just remove the engines key from the package.json of your local install of `pi-camera`. If it seems to be working fine then feel free to make a PR and remove the key across the project. 👍 I don't have the hardware set up to test this anymore so I can't validate if it will work fine on newer versions of node or not.

**Comment by stetsmando** [comment]
@cSchubes any update on this?

**Comment by stetsmando** [comment]
I'm closing this for now. Feel free to make a PR if you want to update that package.
