### ISSUE TITLE
Timeout not being read as a valid option

### ISSUE THREAD

**Issue by cdoern** [stetsmando/pi-camera#12]
I am using the timeout option to make a 20 second long video. My options are:                                 `const myCamera = new PiCamera({
  mode: 'video',
  output: '//home//pi//Videos//video.h264',
  width: 640,
  height: 480,
  timeout: 20000, 
  nopreview: true,
  vflip: true,
});`

throws an error: "Invalid command line option (--timeout)"

**Comment by cdoern** [comment]
I manually removed timeout from the flags.json file and it seems to have fixed the issue. having it in both options and flags does not make sense. If there is a better fix for this please let me know

**Comment by stetsmando** [comment]
Yeah this makes sense. Let me look into this a bit. I think it has to do with some mismatch between the flags and the options but I'm not 100% sure. I haven't looked at this code in well over a year so I need to refresh my memory a bit.

**Comment by stetsmando** [comment]
Yup totally a bug. I'm fixing it now 👍

**Comment by stetsmando** [comment]
Should be fixed now. Pull the latest patched version. I'll leave this open until I've heard back or enough time has passed.

**Comment by stetsmando** [comment]
@cdoern ☝️

**Comment by stetsmando** [comment]
Also I've added a [section](https://github.com/stetsmando/pi-camera#whats-the-difference-between-flags-and-options) on Flags and Options to hopefully help with any confusion
