### ISSUE TITLE
Possible to call start after stop?

### ISSUE THREAD

**Issue by jonaseltes** [stetsmando/pi-camera#13]
Thanks for great lib! 

Seems like there's an error triggered when you try to run start again after stop. Basically I want to be able to change the resolution during runtime. Is there any other way?

Thanks,
Jonas

**Comment by stetsmando** [comment]
@jonaseltes could you provide some example code of how you're trying to accomplish this?

**Comment by jonaseltes** [comment]
Just realised I posted this question in the wrong repo, was intended for another Node Raspberry Pi Camera wrapper.. Product of interacting with too many browser tabs simultaneously. So sorry.

**Comment by stetsmando** [comment]
No worries! 👍
