### ISSUE TITLE
Can This use for real time video capture

### ISSUE THREAD

**Issue by LMJayasundara** [stetsmando/pi-camera#16]

**Comment by stetsmando** [comment]
What does 'real time' video capture mean to you?

**Comment by Shanmax1996** [comment]
Thank for your reply.
I want to show video stream continuously on my browser via localhost..
Can I do it using this library

If can how to do this I mean how to code it..:)
Thank you..

**Comment by stetsmando** [comment]
Ah, okay. So no is the short answer. The interface doesn't actually expose the raw stream for you to consume. You could produce a screenshot at a set interval of time and serve that to the browser. It wouldn't be performant, but at that point you might fair better using the raw python libs.

**Comment by Shanmax1996** [comment]
Hey bro,

can you make a youtube video for how to make node js npm module for OpenCV.
It will help to make another c++ library npm module for node-js...

Thank you, bro

**Comment by stetsmando** [comment]
I've not really put Open CV to the test and don't have any time or desire to produce YouTube content. However, you might look into [OpenCV4NodeJS](https://github.com/justadudewhohacks/opencv4nodejs#readme) that seems to be promising if you're looking into using OpenCV + JavaScript.

**Comment by Shanmax1996** [comment]
ok..thank you, bro

**Comment by Shanmax1996** [comment]
import numpy as np
import cv2 as cv
img = cv.imread
<https://docs.opencv.org/trunk/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56>
('messi5.jpg',0)
rows,cols = img.shape
M = np.float32([[1,0,100],[0,1,50]])
dst = cv.warpAffine
<https://docs.opencv.org/trunk/da/d54/group__imgproc__transform.html#ga0203d9ee5fcd28d40dbc4a1ea4451983>
(img,M,(cols,rows))
cv.imshow
<https://docs.opencv.org/trunk/df/d24/group__highgui__opengl.html#gaae7e90aa3415c68dba22a5ff2cefc25d>
('img',dst)
cv.waitKey
<https://docs.opencv.org/trunk/d7/dfc/group__highgui.html#ga5628525ad33f52eab17feebcfba38bd7>
(0)
cv.destroyAllWindows
<https://docs.opencv.org/trunk/d7/dfc/group__highgui.html#ga6b7fc1c1a8960438156912027b38f481>
()


Can I do this with opencv4nodejs
[image: Annotation 2020-07-01 162022.jpg]
