### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by YorkAARGH** [stetsmando/pi-camera#9]
Is there a way this could return a buffer / bufferArray as well as saving to file?

**Comment by stetsmando** [comment]
Hey @YorkAARGH I'm sure it's possible. Basically what the lib does is execute bash commands on the pi. It uses Node's child process to run those commands and just returns what the output would be to the console if you ran them manually. You can read more about it [here](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback). Also [this](https://github.com/stetsmando/pi-camera/blob/master/index.js#L50) is where that happens in the code. So what could be possible is to initiate the capture of video or an image and then read that from disk as a stream and return the stream. I think having the entire image or video as a buffer could quickly take up too much memory. It's possible, but I don't have any plans on doing that at the moment. I am however, happy to accept pull requests 😀
